version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AWS_REGION=ap-northeast-1
      # ローカル環境のboto3がエラーにならないようにダミーの認証情報を設定
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      # main.pyで判定するための環境変数
      - DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local
    volumes:
      - .:/app # ローカルのコード変更を即座に反映させるため

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8001:8000" # ホスト側からGUI等で確認したい場合は 8001 番を使用
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"

  # DynamoDB Localの中身をブラウザ（GUI）で見るためのツール
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    ports:
      - "8002:8001" # ブラウザから http://localhost:8002 にアクセスする
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local
